### ISSUE TITLE
Toggle menu - feature request

### ISSUE THREAD

**Issue by mariosant** [agorf/lucien#2]
Hi, thanks for lucien!

Would you please consider adding a way to toggle the menu bar? I love the minimal UI, but the menu bar kinda gets in the way.

Thanks again!

**Comment by agorf** [comment]
There is support for full-screen mode (F11) which hides the window title bar and the menu as well. Does that work for you?

**Comment by agorf** [comment]
Thanks for the feedback!

**Comment by mariosant** [comment]
I noticed the full screen functionality, indeed!

Consider the following scenario. When I am participating a meeting and I am taking notes, I usually keep the editor narrow, to the right or left of the conference window. Like the screenshot below.

![image](https://user-images.githubusercontent.com/1409645/63649451-943a5600-c746-11e9-8ced-d8c9e6ef5602.png)

It's really non issue, but I would certainly hide it if there was a way. I can submit a PR if you are interested.

**Comment by agorf** [comment]
My only concern with this is if the user forgets the keyboard shortcut to bring back the menu. Then they will not be able to access it. Maybe a better idea is to provide an auto-hide option and if the cursor is near the top, the menu would slide down.

**Comment by mariosant** [comment]
That would work - might be a bit too complex though. I really like how Firefox toggles menu by hitting "alt". I think other apps bind menu toggle to `alt-m`.

How would you hide the menu bar if you wanted, to your favorite app?

**Comment by agorf** [comment]
Now auto-hiding the menu. It works the same way (shows up with `Alt`).
