### ISSUE TITLE
Text editor widget is resizable

### ISSUE THREAD

**Issue by mariosant** [agorf/lucien#3]
The text editor widget is a resizable textarea. Resizing the editor might be a bit weird, because it leads to unexpected editor positioning. Take a look at the attached screenshot.

![image](https://user-images.githubusercontent.com/1409645/63648723-87186980-c73c-11e9-8498-04d71491478d.png)

I believe this can be solved if a `resize: none` is added to the widget style.

**Comment by agorf** [comment]
Thanks! I knew it was resizable but thought it's not possible to turn it off.

**Comment by mariosant** [comment]
No worries! It's a tricky one!
